name: Receive PR

# read-only repo token
# no access to secrets

on:
  pull_request_target:


jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: rogerluan/label-remover@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}

   
