name: Receive PR

# read-only repo token
# no access to secrets

on:
  pull_request_target:


jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: safetotest

  build:
    name: Build and test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safetotest')
    steps:        
      - uses: actions/checkout@v2    
